### ISSUE TITLE
Clarifying “Pseudo-3D”

### ISSUE THREAD

**Issue by shaunlebron** [metafizzy/zdog-docs#4]
The original description might be [confusing](https://news.ycombinator.com/item?id=20037551):

> Zdog is a pseudo-3D engine. Its geometries exist in 3D space, but are rendered as flat shapes.

If you want something more detailed, perhaps something like this could work?:

> Zdog is a pseudo-3D _Vector Art_ engine.  You define your geometry using 3D splines and blobs, which render as 2D SVG shapes for any arbitrary perspective.
>
> For nerds—this simple translation is made possible by assuming an _orthographic_ projection (where drawing 3D splines becomes trivially reducible to flat 2D splines—not so with _perspective_ projection).  More obvious, the occlusion-culling is achieved with a trivial drawing order or by hiding entire 2D primitives when appropriate.

**Comment by desandro** [comment]
Hello! Thank you for this suggestion. Yeah, I understand how _pseudo-3D_ can be confusing. I appreciate your take on a solution, but I'd rather stick with the copy as is.
